ARG SOURCE_GROUP
ARG SOURCE_REGISTRY
ARG SOURCE_IMAGE
ARG SOURCE_VERSION

FROM $SOURCE_REGISTRY$SOURCE_GROUP$SOURCE_IMAGE:$SOURCE_VERSION

COPY src/rootfs/ /

RUN set -x ;\
  echo "INFO: begin RUN" ;\
  echo "INFO: end RUN"

ENV RUN_LOCAL true
ENV DEFAULT_WORKSPACE /opt/3m

ENTRYPOINT ["/action/lib/linter.sh"]

